export const AminoAcidList = [
  {code: 'his', name: 'histidine'},
  {code: 'ser', name: 'serine'},
  {code: 'arg', name: 'arginine'},
  {code: 'gly', name: 'glycine'},
  {code: 'asp', name: 'aspartic acid'},
  {code: 'glu', name: 'glutamic acid'},
  {code: 'thr', name: 'threonine'},
  {code: 'ala', name: 'alanine'},
  {code: 'hylys', name: 'hydroxylysine'},
  {code: 'pro', name: 'proline'},
  {code: 'cys', name: 'cysteine'},
  {code: 'lys', name: 'lysine'},
  {code: 'tyr', name: 'tyrosine'},
  {code: 'met', name: 'methionine'},
  {code: 'val', name: 'valine'},
  {code: 'ile', name: 'isoleucine'},
  {code: 'leu', name: 'leucine'},
  {code: 'phe', name: 'phenylalanine'},
  {code: 'tau', name: 'taurine'},
  {code: 'gaba', name: 'γ-aminobutyric'},
  {code: 'aaba', name: 'aminoisobutyric acid'},
  {code: 'orn', name: 'ornithine'},
  {code: 'gln', name: 'glutamine'},
  {code: 'asn', name: 'asparagines'},
  {code: 'hypro', name: 'hydroxyproline'},
]